apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketservice
  template:
    metadata:
      labels:
        app: basketservice
    spec:
      containers:
        - name: basketservice
          image: erhanbasaran/basketservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: basket-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: basketservice
  ports:
  - name: basketservice
    protocol: TCP
    port: 80
    targetPort: 80