apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketservice
  template:
    metadata:
      labels:
        app: basketservice
    spec:
      containers:
        - name: basketservice
          image: erhanbasaran/basketservice:latest