apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsupdateservice
  template:
    metadata:
      labels:
        app: productsupdateservice
    spec:
      containers:
      - name: productsupdateservice
        image: nho96/productsupdateservice:latest