apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: rabbitmq-depl 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: rabbitmq 
  template: 
    metadata: 
      labels: 
        app: rabbitmq 
    spec: 
      containers: 
      - name: rabbitmq 
        image: rabbitmq:latest 
        ports: 
          - containerPort: 5672 
        env: 
        - name: RABBITMQ_DEFAULT_USER 
          value: guest 
        - name: RABBITMQ_DEFAULT_PASS 
          value: guest 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: rabbitmq-clusterip-srv 
spec: 
  type: ClusterIP 
  selector: 
    app: rabbitmq 
  ports: 
    - name: amqp 
      protocol: TCP 
      port: 5672 
      targetPort: 5672 